#!/bin/sh

###############################################################################
# F.U.L.L.S.T.O.R.Y common functions and variables
#
# Copyright (C) 2007 F.U.L.L.S.T.O.R.Y Project
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###############################################################################

# Normal color
NORMAL="[0;39m"
# RED: Failure or error message
RED="[1;31m"
# GREEN: Success message
GREEN="[1;32m"
# YELLOW: Descriptions
YELLOW="[1;33m"
# BLUE: System mesages
BLUE="[1;34m"
# MAGENTA: Found devices or drivers
MAGENTA="[1;35m"
# CYAN: Questions
CYAN="[1;36m"
# BOLD WHITE: Hint
WHITE="[1;37m"

###############################################################################

case "$DPKG_ARCH" in
	i?86)
		FLL_ARCH="i686"
		;;
	*)
		FLL_ARCH="$DPKG_ARCH"
		;;
esac

###############################################################################
